### ISSUE TITLE
Clicking on a #somechannel takes 40+ seconds to switch to that channel. 

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#159]
Steps to reproduce:

1. Post a channel `#somechannel` to `#zbay`
2. Click on it.

Expected: the active channel switches from `#zbay` to `#somechannel` immediately, and I see some indication in the channel that messages are loading.

Actual: `#somechannel` appears in left sidebar at the top of the list, but it does not become the active channel for 30 or 40 seconds. I think nothing happened, go do something else, and in 40 seconds I'm suddenly switched to `#somechannel`

**Comment by holmesworcester** [comment]
@NorbertBodziony are you able to reproduce this?

**Comment by NorbertBodziony** [comment]
So that's a flow issue there is a bunch of stuff that we do to import a channel most time-consuming is importing a viewing key that may take up to one minute. Unfortunately we can't do anything about it. I can try to make flow more smooth so user will see indicator of loading messages. Once channel is imported switching to it should be fast.

**Comment by holmesworcester** [comment]
can we create the channel in the UI, switch to it, and show a loading indicator there all steps are complete and messages are loaded?

**Comment by NorbertBodziony** [comment]
That was my initial idea.

**Comment by NorbertBodziony** [comment]
PR #168
