### ISSUE TITLE
Application see new messages only after restart

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/zbay#484]
Description: Zbaylite on Mac did not receive some of the new messages without restarting an application. Some messages go through but most of them do not. On the sender side message is sent and the transaction is included in the block. At the same time, messages sent from the same Mac are sent and received by another user without any problem. Not sure if this is the Mac-specific problem but I wasn't able to replicate the same bug on Windows.

**Comment by holmesworcester** [comment]
Note: we suspect this has to do with a failure to fetch the memo for a given transaction in zecwallet-light-cli.

**Comment by holmesworcester** [comment]
Let's make a ticket in that project and reference here.

**Comment by NorbertBodziony** [comment]
I figured it out, so we are using some cached messages and merge them with new once that caused losing ordering of txns. Cli needs two cycles to fetch memos so if latest transaction does not contain memo we skip it as invalid state and wait for next one. This feature did not work with unsorted messages that's why some messages only appeared after restart of application.
