### ISSUE TITLE
Clicking "try again" does nothing when Tor-connected contact goes offline.

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#586]
Steps to reproduce:

1. Be in an over-tor conversation.
2. Close computer / sleep
3. Reopen computer / wakeup. Contact still appears online.
4. Send message
5. When "try again" error appears, try again. 

Expected: it tries again and gives some visual indication that this is happening.
Actual: it fails. 

A few minutes later, possibly when receiving a reply, I got a white screen frontend error.

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/213678/100647340-5f378e80-330d-11eb-9c5f-997ed9e3eb13.png">

**Comment by holmesworcester** [comment]
update. it looks like messages were sent. possibly as z2z. 
<img width="825" alt="image" src="https://user-images.githubusercontent.com/213678/100647719-eb49b600-330d-11eb-9555-618259879fb5.png">

probably each time i clicked it sent one. but there was no indication at the time that this was happening.

**Comment by vinkabuki** [comment]
I've added some logic, now it switches to zcash immediately after user goes offline and I've fixed resolving addresses, which in some cases were broken and this was causing 'try again' strange behavior. Since I've added these, I couldn't manage to even get 'try again'. Before fix, I've triggered those 'try again' errors, then after I've fixed it, 'try again' behave as expected. So I consider it's done, but we can watch for this too.
