### ISSUE TITLE
Can't register user on windows

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/zbay#604]
Registering users on Windows is not working (tried 3 times). 
On Mac initial registration didn't work but with the first attempt from settings, the user was registered.

**Comment by vinkabuki** [comment]
I've repeated procedure on the same machine, same version, no single modification, and it worked at first try today.

**Comment by vinkabuki** [comment]
The problem was that when requesting money, znode-aws was firing 10 actions in a row (very fast). Because of this was happening fast and without waiting for any results, not all of them were handled properly. If you are unlucky, all of them fail, you don't get any funds and UTXO, and user registration fails.

**Comment by kingalg** [comment]
I didn't encounter this bug in updated version, so I'm closing this.
