### ISSUE TITLE
Zbay channel not visible right after fresh install

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/zbay#729]
Zbay channel is not visible right after fresh install - it apears only after the zbay is sync which takes a few minutes.

**Comment by holmesworcester** [comment]
solution is to stay in "loading" state until we have loaded at least one (or maybe all if we can know?) channel from orbitdb

**Comment by EmiM** [comment]
This is a problem with blocking syncing. It should be syncing in the background. Right now public channel messages are not pulled from waggle until blockchain is fully synced, that's why it takes so long.

**Comment by EmiM** [comment]
https://github.com/ZbayApp/ZbayLite/pull/228
https://github.com/ZbayApp/waggle/pull/18
I didn't removed/moved syncing, I didn't add loader BUT I improved and changed few things. 

The change is already in version 3.2.7 but I would love to hear a feedback from @kingalg because maybe we don't need any loader animation anymore.

**Comment by kingalg** [comment]
It was quite fast on both systems in version v 3.2.7. I'm closing this task and I will re-open it if in the future this problem reoccure.
