### ISSUE TITLE
New message sync for returning user doesn't happen until user sends a message

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#733]
steps to reproduce:

1. join channel with orbitdb messages and other peers online.
2. go offline.
3. send messages to the channel from another computer
4. come back online 

expected: messages sent while offline sync
actual: messages only sync once the returning client sends a message. then they all sync.

**Comment by holmesworcester** [comment]
a way to force this issue to happen is to send many messages in a row on the channel, with both clients connected.

eventually, the receiving client will stop receiving messages. then, when they send, they'll receive them.

**Comment by holmesworcester** [comment]
@EmiM Is this fix in yesterday's build?

I'm still seeing this problem in yesterday's build of Zbay, so I'm moving it back to "blocks release".

If it's fixed and I'm just not using the right build, can you provide me a build with the fix so I can test?

**Comment by EmiM** [comment]
It's possible that I missed something while implementing previous fix. https://github.com/ZbayApp/ZbayLite/pull/219/

**Comment by holmesworcester** [comment]
@EmiM I'm using https://s3.amazonaws.com/release.zbay.lite.waggle/Zbay-3.2.6-zbay-lite.AppImage on linux and I still see this problem.

**Comment by holmesworcester** [comment]
to be clear about the steps I'm following, i'm quitting in client A, sending in client B, and then opening client A. 

client B's message isn't received until i send in client A.

**Comment by EmiM** [comment]
Actually now as I am thinking about it, it is possible. It's because current setup doesn't guarantee the proper order which should be:
* connect websockets (waggle <-> zbaylite)
* initialize waggle (orbitdb)
* process with handling db events, pulling data from waggle etc.
So I think what happens is when you start the app, zbay subscribes to your channels **before** websockets are connected and that's why messages are not pulled for the first time. Sending a message subscribes to the channel again (but only once) and pulls messages. 
We are currently working on correcting the order and it should fix multiple issues https://github.com/ZbayApp/ZbayLite/pull/228

**Comment by holmesworcester** [comment]
i haven't seen this issue in a while and i think it's probably fixed. closing.
