### ISSUE TITLE
"Not fully synced..." alert flashes when switching back to zbay tab

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#803]
Steps:

1. Switch to a DM conversation
2. Switch back to zbay channel 

expected: i just see channel content.
actual: the "not fully synced..." alert message flashes on the screen for a fraction of a second, causing content to jump.

**Comment by holmesworcester** [comment]
This perhaps shouldn't be "blocks release" but it is weird and broken.

**Comment by vinkabuki** [comment]
@holmes. This issue is related to https://github.com/ZbayApp/zbay/issues/794, I suggest prioritize this and we will save a lot of time in the future. Lags when switching between direct and public channels, wrong channel input text in the past, this one, issue with not updating state properly, I've fixed last week are all caused because we have separate components for direct and public channel and I see no reason why not create one which will be consistent and won't cause weird unexpected bugs

**Comment by vinkabuki** [comment]
So I suggest not fixing this in current release, but prioritize it in the next.

**Comment by holmesworcester** [comment]
That seems fine to me. Especially since we are already updating the style and text of this message, right?
